from rich import print
from rich.panel import Panel
from rich.table import Table

# Project metadata
my_dict = {
    "project_name": "{{ cookiecutter.project_name }}",
    "project_slug": "{{ cookiecutter.project_slug }}",
    "author": "{{ cookiecutter.author_name }}",
    "description": "{{ cookiecutter.description }}",
    "python_version": "{{ cookiecutter.python_version }}"
}

# Sample data
my_list = [1, "apple", {"key": "value"}, True, None, 3.14]

print("--- Rich Printing ---")
print(my_dict)
print(my_list)

# Welcome panel
print(Panel(
    f"Hello, [bold magenta]{{ cookiecutter.project_name }}[/]!",
    title="[bold green]Welcome to {{ cookiecutter.project_name }}[/]",
    subtitle="Generated by Cookiecutter"
))

# Task overview table
table = Table(title="{{ cookiecutter.project_name }} Task Overview")

table.add_column("ID", style="dim", width=6)
table.add_column("Task Name")
table.add_column("Status", justify="right")

table.add_row("1", "Initialize Repository", "[green]Done[/]")
table.add_row("2", "Configure Pre-commit Hooks", "[yellow]In Progress[/]")
table.add_row("3", "Start Development", "[red]Pending[/]")

print(table)